### PR TITLE
#144122589 : return dashboard URL when provisioning service

### PR DESCRIPTION
**Pull request by rohitsharma04**

### CODE REVIEW

**Comment by boyang9527** [comment]
There are a few things from my understanding, correct me if I am wrong
1. Dashboard client is not a must, this can be preconfigured in service dashboard instead of cloud controller to create when the service is added
2. Dashboard URL can be configured separately, not depending on dashboard client

**Comment by rohitsharma04** [comment]
@boyang9527 I agree, I'll update the PR.

**Comment by rohitsharma04** [comment]
@boyang9527 updated the PR.

**Comment by boyang9527** [comment]
@rohitsharma04  thanks! LGTM

**Comment by qibobo** [comment]
LGTM

**Comment by paltanmoy** [comment]
LGTM

**Pull request merged**
