### PR TITLE
140444445: Fixed unreachable request to Scheduler application.

### PR DESCRIPTION
**Pull request by kanekoh**
Just for Information.
We observed the message 'Started SchedulerApplication in' is appearing twice after applying Spring Cloud Consul.
First time appears even before tomcat has started which could lead to invalid test so we have changed the message in component.go and We will investigate this in a separate story.

### CODE REVIEW

**Comment by fraenkel** [comment]
If you introduced the issue with this change then the fix needs to be apart of this PR.

**Comment by kanekoh** [comment]
Issue was because of multiple dependencies.

**Comment by fraenkel** [comment]
I don't see where you disable registering the health check.

**Comment by kanekoh** [comment]
When I disabled registering the health check, Consul had no checks for scheduler even scheduler was down.

When Spring Cloud Consul is set both parameters 'spring.cloud.consul.discovery.registerHealthCheck=false' and 'spring.cloud.consul.discovery.heartbeat.enabled=true' and Spring Cloud Consul couldn't be completed to register scheduler to consul because Consul agent has no checks for scheduler.

Scheduler had no CLOSE_WAIT connections when Consul agent had checks for scheduler with TTL and noticed if scheduler was down or not.
So, I set the parameters 'spring.cloud.consul.discovery.registerHealthCheck=true' (default) and 'spring.cloud.consul.discovery.heartbeat.enabled=true' to Spring Cloud Consul.

**Comment by fraenkel** [comment]
weird, the docs say otherwise but that is fine for now.

**Pull request merged**
