### PR TITLE
Introduce DB app to auto-scaler deployment

### PR DESCRIPTION
**Pull request by pradyutsarma**

### CODE REVIEW

**Comment by fraenkel** [comment]
1. Can you squash the commits.
2. Why do we require java-buildpack v3.7?

**Comment by pradyutsarma** [comment]
@fraenkel Will it be possible for you to use the option of "Squash and Merge" from the Github UI when you merge the PR?

**Comment by fraenkel** [comment]
I can do that but I would rather folks deliver commits properly. I don't mind multiple commits if they are for separate functions but these 3 should be delivered as one.
The moment I squash, it will not reflect that it came from you.

**Comment by fraenkel** [comment]
Manually merged.

**Comment by pradyutsarma** [comment]
@fraenkel I see that you've squashed and merged the commit. Thanks !!

Regarding your query regarding using buildpack version 3.7, See this thread here https://github.com/spring-projects/spring-boot/issues/4897 for more details on it.
We're using spring-boot 1.4.0 for the db app and hence need buildpack 3.7.

**Pull request closed without merging**
