### PR TITLE
149082123: VMs start running even if the db url/credentials is incorrect or db is unreachable

### PR DESCRIPTION
**Pull request by ghaih**
@boyang9527 As discussed on slack, please review, Rest of the discussion can be done on tracker story.

### CODE REVIEW

**Comment by cdlliuy** [comment]
@ghaih , the tracker issue said :when the individual components are deployed, each of them should check whether the DB is reachable and should fail to start in case of an unreachable DB or incorrect credentials.

so, the PR is only address the scheduler part, right ? are you planning to go forward to cover each component?

**Comment by ghaih** [comment]
@cdlliuy , Thats right scheduler only handled here, thats why didnot change story status. I guess go components are fine. Rest of components can be take up by anyone.

**Comment by boyang9527** [comment]
I saw you are detecting whether there is db initialization issue by capturing the jdbc exceptions. Are there any other possibilities than jdbc exception  that we need to exit  for scheduler? 

Did you observe the process exit when bosh deploy scheduler with a wrong db setting?

**Comment by ghaih** [comment]
The unit test worked fine with the incorrect db setting, but the bosh deploy worked ok. That was my concern which I wanted to understand why the depoly does not fail.

**Comment by boyang9527** [comment]
@ghaih  I will try to deploy with a wrong db setting and see what happens...

**Comment by ghaih** [comment]
Cannot think of any other exception that would require an exit.

**Comment by boyang9527** [comment]
@ghaih I tested this PR with cf-deployment.  The scheduler job only failed when spring.datasource.url / username / password is not set correctly...  it still starts successfully when spring.policyDbDataSource is incorrect. 

So looks like scheduler only checks db settings for application and quartz, not for policy

**Comment by ghaih** [comment]
@boyang9527 , Thanks for letting me know. I will look at it once I get a chance.

**Comment by cdlliuy** [comment]
Close this PR as it is an incomplete solution, and will drive it further in another PR.

**Pull request closed without merging**
