### PR TITLE
Retry metrics polling and requisite tests

### PR DESCRIPTION
**Pull request by pradyutsarma**

### CODE REVIEW

**Comment by fraenkel** [comment]
There are multiple issues here.
1. We don't need to add yet another package to do a simple for loop.
2. We are not making the retries configurable. It should just be a constant.
3. We want to be selective on when we retry. If you dig deeper you will see that noaa library is broken in this regard.

**Comment by pradyutsarma** [comment]
Got the first two points.
For 3) Saw this issue https://github.com/cf-tm-bot/loggregator/issues/146 and a PR https://github.com/cloudfoundry/cli/pull/966 for the CF CLI. Do we emulate something similar based on the (retry)error codes then?

**Comment by fraenkel** [comment]
Not quite. Those are strictly for token refresh which happens under the covers. With bosh-lite try different failures like take down your dopplers, or your traffic controller, what errors do you get back?

**Comment by pradyutsarma** [comment]
Closing the PR. Will create a separate one once we have the noaa issue resolved. More details in conversation here https://www.pivotaltracker.com/story/show/127404259

**Pull request closed without merging**
