### PR TITLE
#140295751: Removed unused table applicationmetrics

### PR DESCRIPTION
**Pull request by rohitsharma04**

### CODE REVIEW

**Comment by fraenkel** [comment]
Good catch. Since we haven't shipped a release, one can get away with just deleting the table from the changelog rather than dropping which would be needed if we weren't rebuilding the dbs.

**Comment by rohitsharma04** [comment]
Should I delete the table from the existing changeset and update the PR ?

**Comment by fraenkel** [comment]
Yes.
Before we release v1, we will review the changelog and go to a single entry per log.
There is no point in having the db do more than it needs until we absolutely need to.

**Comment by rohitsharma04** [comment]
Updated.

**Pull request merged**
