### PR TITLE
Adopt to JSON formatting for logs

### PR DESCRIPTION
**Pull request by pradyutsarma**
Below are examples of:
1. Info logs
```
2016-08-29T20:20:14.01+0530 [App/0]      OUT Policy creation request received {
2016-08-29T20:20:14.01+0530 [App/0]      OUT   "app id": "had"
2016-08-29T20:20:14.01+0530 [App/0]      OUT }
```
and,
2. Error logs
```
2016-08-29T20:18:45.86+0530 [App/0]      ERR Input policy JSON has incompatible values {
2016-08-29T20:18:45.86+0530 [App/0]      ERR   "app id": "had",
2016-08-29T20:18:45.86+0530 [App/0]      ERR   "error": [
2016-08-29T20:18:45.86+0530 [App/0]      ERR     {
2016-08-29T20:18:45.86+0530 [App/0]      ERR       "property": "specific_date.start_date_time",
2016-08-29T20:18:45.86+0530 [App/0]      ERR       "message": "specific_date.start_date_time and specific_date.end_date_time values are not compatible",
2016-08-29T20:18:45.86+0530 [App/0]      ERR       "instance": {
2016-08-29T20:18:45.86+0530 [App/0]      ERR         "start_date_time": "2015-07-02T10:00",
2016-08-29T20:18:45.86+0530 [App/0]      ERR         "end_date_time": "2015-06-15T13:59",
2016-08-29T20:18:45.86+0530 [App/0]      ERR         "instance_min_count": 1,
2016-08-29T20:18:45.86+0530 [App/0]      ERR         "instance_max_count": 4,
2016-08-29T20:18:45.86+0530 [App/0]      ERR         "initial_min_instance_count": 2
2016-08-29T20:18:45.86+0530 [App/0]      ERR       },
2016-08-29T20:18:45.86+0530 [App/0]      ERR       "stack": "start_date_time 2015-07-02T10:00 is same or after end_date_time 2015-06-15T13:59 in specific_date :[0]"
2016-08-29T20:18:45.86+0530 [App/0]      ERR     }
2016-08-29T20:18:45.86+0530 [App/0]      ERR   ]
2016-08-29T20:18:45.86+0530 [App/0]      ERR }
```

### CODE REVIEW

**Comment by fraenkel** [comment]
This won't work.
Having log lines broken across multiple lines is a problem for Loggregator.

**Comment by pradyutsarma** [comment]
@fraenkel  Are you then proposing that we just log the json without the formatting, if we have to maintain the line integrity. And users use a separate tool/parser to pretty-print it later.

**Comment by fraenkel** [comment]
@pradyutsarma logging is to be machine consumable not necessarily human readable.
If you look at all the logging that is currently done by CF as well as Docker and others, a line is a single log complete log statement unless it goes over some maximum threshold. That single line should be parseable. What you have is neither parseable nor a single line.

**Comment by pradyutsarma** [comment]
Fixed by doing an explicit util.format to avoid any console.log/error pretty printing going into multiple lines. The logs look something like this now.
```
2016-08-30T15:12:08.84+0530 [App/0]      ERR Input policy JSON has incompatible values {"app id":"hsd","error":[{"property":"recurring_schedule.instance_min_count","message":"recurring_schedule.instance_min_count and recurring_schedule.instance_max_count values are not compatible","instance":{"start_time":"11:00","end_time":"19:30","days_of_month":[10,20,30],"instance_min_count":10,"instance_max_count":10},"stack":"instance_min_count 10 is higher or equal to instance_max_count 10 in recurring_schedule :[3]"}]}
2016-08-30T15:12:08.84+0530 [RTR/0]      OUT autoscaler-api.bosh-lite.com - [30/08/2016:09:42:08.831 +0000] "PUT /v1/apps/hsd/policy HTTP/1.1" 400 2442 443 "-" "-" 10.244.0.34:54582 x_forwarded_for:"192.168.50.1, 10.244.0.34" x_forwarded_proto:"http" vcap_request_id:bfc8945d-497f-464b-469b-0588e70f3550 response_time:0.017508928 app_id:ae246b8f-d868-4c6b-93d1-a03e6780124c
```

**Comment by fraenkel** [comment]
This is better but still not right. I don't see how you can parse that APP line.  Ignore how RTR looks since that follows NCSA logging rules.

Let me give you some concrete examples. We need to do this for all of our processes.
For Go processes, we have logs that will look like
```
{"timestamp":"1472485354.146095514","source":"bbs","message":"bbs.registration-runner.poll-until-signaled.started","log_level":1,"data":{"service":"bbs","session":"8.1","update-interval":"1.5s"}}
```
For ruby, we have:
```
{"timestamp":1472484812.9521208,"message":"Installing buildpack nodejs_buildpack","log_level":"info","source":"cc.background","data":{},"thread_id":47041201205520,"fiber_id":47041237626080,"process_id":4576,"file":"/var/vcap/data/packages/cloud_controller_ng/101f5dcdc3e53c8850855976ac8f320b9174d5c9.1-de9c4f55f8931a6c8340a68aab913203d77ce7bd/cloud_controller_ng/app/jobs/runtime/buildpack_installer.rb","lineno":15,"method":"perform"}
```

For Node and Java, it should match.

**Comment by pradyutsarma** [comment]
@fraenkel Ok. Now I understand. The logs should be readable via an external data analyser. I was confused as to how we would achieve this with the Commons log format. So, what about having something like below,
```
{"timestamp":1472484812.9521208,"source":"apiserver","text":"Input policy JSON has incompatible values","log_level":"error","data":{"app id":"hsd","error":[{"property":"recurring_schedule.instance_min_count","message":"recurring_schedule.instance_min_count and recurring_schedule.instance_max_count values are not compatible","instance":{"start_time":"11:00","end_time":"19:30","days_of_month":[10,20,30],"instance_min_count":10,"instance_max_count":10},"stack":"instance_min_count 10 is higher or equal to instance_max_count 10 in recurring_schedule :[3]"}]}}
```
We could also include app instance ids and more details if required.

**Comment by fraenkel** [comment]
We won't worry about additional details. If the logs are off-loaded, that process would encode the additional details.
But the above looks good. Now we need something for Java.

**Comment by fraenkel** [comment]
Service broker?

**Comment by pradyutsarma** [comment]
I'll target the scheduler and the broker via separate stories.

**Pull request merged**
