### PR TITLE
#150479587: Broken threshold value validation for 'memoryutil' metrics types

### PR DESCRIPTION
**Pull request by rohitsharma04**

### CODE REVIEW

**Comment by qibobo** [comment]
For the scaling rules below, the "memoryused" has two lower rules. Is is a valid policy?
"scaling_rules":[
      {
         "metric_type":"memoryused",
         "stat_window_secs":300,
         "breach_duration_secs":600,
         "threshold":30,
         "operator":"<",
         "cool_down_secs":300,
         "adjustment":"-1"
      },
      {
         "metric_type":"memoryused",
         "stat_window_secs":300,
         "breach_duration_secs":600,
         "threshold":40,
         "operator":"<",
         "cool_down_secs":300,
         "adjustment":"+1"
      }
   ]

**Comment by rohitsharma04** [comment]
@qibobo the above policy does seem a little weird.
correct me if I'm wrong but I guess you can have a policy like
```json
"scaling_rules":[
{
  "metric_type":"memoryused",
  "stat_window_secs":300,
  "breach_duration_secs":600,
  "threshold":30,
  "operator":"<",
  "cool_down_secs":300,
  "adjustment":"-2"
},
{
  "metric_type":"memoryused",
  "stat_window_secs":300,
  "breach_duration_secs":600,
  "threshold":40,
  "operator":"<",
  "cool_down_secs":300,
  "adjustment":"-1"
}]
```
So if the memory usage go below 30 MB scale down by 2 instances but if it's less than 40 MB then scale down by only 1 instance. So you can have multiple lower rules for the same metric_type.

**Comment by qibobo** [comment]
@rohitsharma04  ok. got it.

**Comment by qibobo** [comment]
LGTM

**Pull request merged**
