### PR TITLE
31-fix-date-parsing Use a date format that matches the observed time.

### PR DESCRIPTION
**Pull request by ericpromislow**
This is needed to prevent the autoscaler server from throwing NullPointerExceptions

### CODE REVIEW

**Comment by fraenkel** [comment]
I am a bit confused how you are seeing a different timestamp.
If I issue the stats endpoint, I get the following back:
"usage": {
            "time": "2016-05-31 14:47:49 +0000",
            "cpu": 0.004092637867367473,
            "mem": 49086464,
            "disk": 0
         }

The code does `"time" => Time.now.to_s` which corresponds to the above and ruby docs.

**Comment by ericpromislow** [comment]
It's possible that this is only an error in the cfibmers repository. I was observing timestamps of the form 
"2016-05-31T14:47:49.123456789Z..." that didn't match the format. (And I can't be more specific on the part after the "Z" -- I'm working on a different branch and had to zap the VMs with autoscaling.)  So I'll close this PR: no need to update on this repo.

Are you taking PRs for the cfibmers repository or will we need to fork it until app-autoscaling is ready for general use?

**Comment by fraenkel** [comment]
This error shouldn't be isolated to that repo. It is the same code.
Are you using DEA or Diego?
This repo is ahead of cfibmers, but does not have BOSH support.

All issues should be reported here.

**Comment by ericpromislow** [comment]
We're using diego.

**Comment by fraenkel** [comment]
That might explain the difference. Let me check out diego.

**Comment by fraenkel** [comment]
@ericpromislow Diego is serializing a time.Time which will be in RFC 3339 format with sub-second precision. To support Diego, this is needed but I would like to have tests that show both the Ruby format and the RFC 3339 format are both properly handled.

**Comment by ericpromislow** [comment]
I've working on a patch to CFInstanceStats to handle both kinds of dates. There's no way to configure this -- the autoscaler is a singleton that services both diego apps and DEA apps at the same time. Is there a directory in app-autoscaler/server/src/test I should put these tests in, or would new tests be needed?

**Comment by fraenkel** [comment]
I would just create a new file named server/src/test/java/org/cloudfoundry/autoscaler/metric/bean/CFInstanceStatsTest.java.

Don't worry about backfilling, just focus on the new function you are adding.

**Comment by satoyan** [comment]
When will this PR be merged?

**Comment by fraenkel** [comment]
I am going to close this since it no longer applies to the new code base.
If you disagree, just reopen it with comments.

**Pull request closed without merging**
