### PR TITLE
Remove toLowerCase from dbUri in apiserver and broker settings

### PR DESCRIPTION
**Pull request by pradyutsarma**
Fixes https://www.pivotaltracker.com/story/show/145872219

### CODE REVIEW

**Comment by pradyutsarma** [comment]
The failure is in this context/test https://github.com/cloudfoundry-incubator/app-autoscaler/blob/develop/api/test/unit/config/settings_test.js#L235-L236
Can somebody tell me if we really need this test or can I just remove it from both the apiserver and the servicebroker?

**Comment by pradyutsarma** [comment]
I took the liberty of removing the db mixed-to-lowercase tests from both the servicebroker and the apiserver. Will create a separate chore to look discuss https://github.com/cloudfoundry-incubator/app-autoscaler/blob/develop/api/lib/config/setting.js#L20

**Comment by boyang9527** [comment]
cleanUpUri is used by the following:
lib/config/setting.js:  settingsObj.scheduler.uri = cleanUpUri(settingsObj.scheduler.uri);
lib/config/setting.js:  settingsObj.scalingEngine.uri = cleanUpUri(settingsObj.scalingEngine.uri);

since there is no usenrame:password in these two uri, so this should be fine.. while I guess we can remove the toLowerCase() in case it will be used by other places.

**Comment by boyang9527** [comment]
LGTM

**Pull request merged**
