### PR TITLE
refactor code for helpers

### PR DESCRIPTION
**Pull request by boyang9527**

### CODE REVIEW

**Comment by cdlliuy** [comment]
LGTM

**Comment by cdlliuy** [comment]
@boyang9527 , but there are conflicts now ...

**Comment by boyang9527** [comment]
@cdlliuy  rebased

**Comment by boyang9527** [comment]
@cdlliuy @qibobo  they were caused by a dirty workspace from the circuit breaker branch..

I did a force push and they were fixed.

**Comment by qibobo** [comment]
LGTM

**Pull request merged**
